namespace BoardGameRules.Entities.Actions;

public enum CantUseBuildActionReason
{
	NO_MORE_INDUSTRIES_TO_BUILD = 1,
	CAN_BUILD_IN_CANAL_ERA_ONLY = 2,
	CAN_BUILD_IN_RAIL_ERA_ONLY = 3,
	NO_PLACE_TO_BUILD_INDUSTRY_IN_THE_SLOT = 4,
	ONLY_ONE_INDUSTRY_IN_REGION = 5,
	NO_VALID_CARD_TO_BUILD = 6,
	NO_MONEY = 7,
	NO_MONEY_COAL = 8,
	NO_MONEY_IRON = 9,
	NO_COAL = 10,
	NO_IRON = 11,
	NO_PLACE_TO_BUILD_INDUSTRY_ON_BOARD = 112,
	INVALID_INDUSTRY_TYPE = 13,
	NOT_IN_PERSONAL_NETWORK = 14,
	NO_REASON = 15,
	FIRST_BUILD_IN_SINGLE_SLOT = 16
}
